/**
 * POST /api/flashcards/bulk
 * Create multiple flashcards at once (after AI generation)
 *
 * This endpoint is used to save flashcards that were generated by AI
 * and approved by the user. It updates the generation record with
 * accepted counts and creates the flashcard records.
 *
 * This endpoint requires authentication via Supabase JWT token.
 */

import type { APIContext } from "astro";
import { BulkCreateFlashcardsHandler } from "@/lib/api-handlers/flashcards/BulkCreateFlashcardsHandler";

// Disable prerendering for this API route
export const prerender = false;

/**
 * POST handler for bulk flashcard creation
 */
export async function POST(context: APIContext): Promise<Response> {
  return new BulkCreateFlashcardsHandler().handle(context);
}
